<?php

return [
    'admin_email' => env('ADMIN_EMAIL'),
    'stripe' => [
        'publishable' => env('STRIPE_PUBLISHABLE_KEY'),
        'secret' => env('STRIPE_SECRET_KEY'),
        'webhook_secret' => env('STRIPE_WEBHOOK_SECRET_KEY'),
    ],
    'transferwise' => [
        'sandbox' => env('TRANSFERWISE_SANDBOX'),
        'profile_id' => env('TRANSFERWISE_PROFILE_ID'),
        'key' => env('TRANSFERWISE_KEY'),
        'private_pem' => env('TRANSFERWISE_PRIVATE_PEM'),
    ],
    'transferwise_payout_currencies' => [
        'eur' => ['currency'=> 'EUR', 'recipient_type' => 'iban'],
        'gbp' => ['currency'=> 'GBP (United Kingdom)', 'recipient_type' => 'sort_code'],
        'usd' => ['currency'=> 'USD (United States)', 'recipient_type' => 'aba'],
        'chf' => ['currency'=> 'CHF (Switzerland)', 'recipient_type' => 'iban'],
        'czk' => ['currency'=> 'CZK (Czech Republic)', 'recipient_type' => 'iban'],
        'dkk' => ['currency'=> 'DKK (Denmark)', 'recipient_type' => 'iban'],
        'hrk' => ['currency'=> 'HRK (Croatia)', 'recipient_type' => 'iban'],
        'huf' => ['currency'=> 'HUF (Hungary)', 'recipient_type' => 'iban'],
        'nok' => ['currency'=> 'NOK (Norway)', 'recipient_type' => 'iban'],
        'pln' => ['currency'=> 'PLN (Poland)', 'recipient_type' => 'iban'],
        'sek' => ['currency'=> 'SEK (Sweden)', 'recipient_type' => 'iban'],
    ],
    'transferwise_payout_currencies_twill' => [
        ['value' => 'eur', 'label' => 'EUR'],
        ['value' => 'gbp', 'label' => 'GBP (United Kingdom)'],
        ['value' => 'usd', 'label' => 'USD (United States)'],
        ['value' => 'chf', 'label' => 'CHF (Switzerland)'],
        ['value' => 'czk', 'label' => 'DKK (Denmark)'],
        ['value' => 'dkk', 'label' => 'HRK (Croatia)'],
        ['value' => 'hrk', 'label' => 'HUF (Hungary)'],
        ['value' => 'huf', 'label' => 'HUF (Hungary'],
        ['value' => 'nok', 'label' => 'NOK (Norway)'],
        ['value' => 'pln', 'label' => 'PLN (Poland)'],
        ['value' => 'sek', 'label' => 'SEK (Sweden)'],
    ],
    'found_source' => [
        ['value' => 'search_engine', 'label' => 'Search engine'],
        ['value' => 'word_of_mouth',  'label' => 'Word of mouth'],
        ['value' => 'blog',  'label' => 'Blog post'],
        ['value' => 'social_media',  'label' => 'Social media'],
        ['value' => 'tv',  'label' => 'TV'],
        ['value' => 'radio',  'label' => 'Radio'],
    ],
    'join_reasons' => [
        [
            'value' => 'living_abroad_looking_job',
            'label' => 'I am living abroad and looking for work'
        ],
        [
            'value' => 'full_time_work_extra_work',
            'label' => 'I work full time in childcare and would like some extra work'
        ],
        [
            'value' => 'find_nanny_job',
            'label' => 'I would like to find a holiday nanny job'
        ],
        [
            'value' => 'travel_often_nanny_when_travel',
            'label' => 'I travel often and would like to babysit and nanny abroad while I travel'
        ],
        [
            'value' => 'live_popular_destination',
            'label' => 'I live in a popular tourist destination and would like to find work as a babysitter'
        ],
        [
            'value' => 'studying_training_experience',
            'label' => 'I am studying or training in childcare and would like some more experience with children'
        ],
    ],
    'experience_years' => [
        ['value' => 0,  'label' => 'No experience'],
        ['value' => 1,  'label' => '1 year'],
        ['value' => 2,  'label' => '2 years'],
        ['value' => 3,  'label' => '3 years'],
        ['value' => 4,  'label' => '4 years'],
        ['value' => 5,  'label' => '5-10 years'],
        ['value' => 11,  'label' => '11+ years'],
    ],
    'experience_age_groups' => [
        ['value' => '0', 'label' => '0-1 years'],
        ['value' => '1', 'label' => '1-3 years'],
        ['value' => '4', 'label' => '4-7 years'],
        ['value' => '8', 'label' => '8-11 years'],
        ['value' => '12', 'label' => '12+ years'],
    ],
    'languages' => [
        'ab' => 'Abkhazian',
        'aa' => 'Afar',
        'af' => 'Afrikaans',
        'ak' => 'Akan',
        'sq' => 'Albanian',
        'am' => 'Amharic',
        'ar' => 'Arabic',
        'an' => 'Aragonese',
        'hy' => 'Armenian',
        'as' => 'Assamese',
        'av' => 'Avaric',
        'ae' => 'Avestan',
        'ay' => 'Aymara',
        'az' => 'Azerbaijani',
        'bm' => 'Bambara',
        'ba' => 'Bashkir',
        'eu' => 'Basque',
        'be' => 'Belarusian',
        'bn' => 'Bengali',
        'bh' => 'Bihari languages',
        'bi' => 'Bislama',
        'bs' => 'Bosnian',
        'br' => 'Breton',
        'bg' => 'Bulgarian',
        'my' => 'Burmese',
        'ca' => 'Catalan, Valencian',
        'km' => 'Central Khmer',
        'ch' => 'Chamorro',
        'ce' => 'Chechen',
        'ny' => 'Chichewa, Chewa, Nyanja',
        'zh' => 'Chinese',
        'cu' => 'Church Slavonic, Old Bulgarian, Old Church Slavonic',
        'cv' => 'Chuvash',
        'kw' => 'Cornish',
        'co' => 'Corsican',
        'cr' => 'Cree',
        'hr' => 'Croatian',
        'cs' => 'Czech',
        'da' => 'Danish',
        'dv' => 'Divehi, Dhivehi, Maldivian',
        'nl' => 'Dutch, Flemish',
        'dz' => 'Dzongkha',
        'en' => 'English',
        'eo' => 'Esperanto',
        'et' => 'Estonian',
        'ee' => 'Ewe',
        'fo' => 'Faroese',
        'fj' => 'Fijian',
        'fi' => 'Finnish',
        'fr' => 'French',
        'ff' => 'Fulah',
        'gd' => 'Gaelic, Scottish Gaelic',
        'gl' => 'Galician',
        'lg' => 'Ganda',
        'ka' => 'Georgian',
        'de' => 'German',
        'ki' => 'Gikuyu, Kikuyu',
        'el' => 'Greek (Modern)',
        'kl' => 'Greenlandic, Kalaallisut',
        'gn' => 'Guarani',
        'gu' => 'Gujarati',
        'ht' => 'Haitian, Haitian Creole',
        'ha' => 'Hausa',
        'he' => 'Hebrew',
        'hz' => 'Herero',
        'hi' => 'Hindi',
        'ho' => 'Hiri Motu',
        'hu' => 'Hungarian',
        'is' => 'Icelandic',
        'io' => 'Ido',
        'ig' => 'Igbo',
        'id' => 'Indonesian',
        'ia' => 'Interlingua (International Auxiliary Language Association)',
        'ie' => 'Interlingue',
        'iu' => 'Inuktitut',
        'ik' => 'Inupiaq',
        'ga' => 'Irish',
        'it' => 'Italian',
        'ja' => 'Japanese',
        'jv' => 'Javanese',
        'kn' => 'Kannada',
        'kr' => 'Kanuri',
        'ks' => 'Kashmiri',
        'kk' => 'Kazakh',
        'rw' => 'Kinyarwanda',
        'kv' => 'Komi',
        'kg' => 'Kongo',
        'ko' => 'Korean',
        'kj' => 'Kwanyama, Kuanyama',
        'ku' => 'Kurdish',
        'ky' => 'Kyrgyz',
        'lo' => 'Lao',
        'la' => 'Latin',
        'lv' => 'Latvian',
        'lb' => 'Letzeburgesch, Luxembourgish',
        'li' => 'Limburgish, Limburgan, Limburger',
        'ln' => 'Lingala',
        'lt' => 'Lithuanian',
        'lu' => 'Luba-Katanga',
        'mk' => 'Macedonian',
        'mg' => 'Malagasy',
        'ms' => 'Malay',
        'ml' => 'Malayalam',
        'mt' => 'Maltese',
        'gv' => 'Manx',
        'mi' => 'Maori',
        'mr' => 'Marathi',
        'mh' => 'Marshallese',
        'ro' => 'Moldovan, Moldavian, Romanian',
        'mn' => 'Mongolian',
        'na' => 'Nauru',
        'nv' => 'Navajo, Navaho',
        'nd' => 'Northern Ndebele',
        'ng' => 'Ndonga',
        'ne' => 'Nepali',
        'se' => 'Northern Sami',
        'no' => 'Norwegian',
        'nb' => 'Norwegian Bokmål',
        'nn' => 'Norwegian Nynorsk',
        'ii' => 'Nuosu, Sichuan Yi',
        'oc' => 'Occitan (post 1500)',
        'oj' => 'Ojibwa',
        'or' => 'Oriya',
        'om' => 'Oromo',
        'os' => 'Ossetian, Ossetic',
        'pi' => 'Pali',
        'pa' => 'Panjabi, Punjabi',
        'ps' => 'Pashto, Pushto',
        'fa' => 'Persian',
        'pl' => 'Polish',
        'pt' => 'Portuguese',
        'qu' => 'Quechua',
        'rm' => 'Romansh',
        'rn' => 'Rundi',
        'ru' => 'Russian',
        'sm' => 'Samoan',
        'sg' => 'Sango',
        'sa' => 'Sanskrit',
        'sc' => 'Sardinian',
        'sr' => 'Serbian',
        'sn' => 'Shona',
        'sd' => 'Sindhi',
        'si' => 'Sinhala, Sinhalese',
        'sk' => 'Slovak',
        'sl' => 'Slovenian',
        'so' => 'Somali',
        'st' => 'Sotho, Southern',
        'nr' => 'South Ndebele',
        'es' => 'Spanish',
        'su' => 'Sundanese',
        'sw' => 'Swahili',
        'ss' => 'Swati',
        'sv' => 'Swedish',
        'tl' => 'Tagalog',
        'ty' => 'Tahitian',
        'tg' => 'Tajik',
        'ta' => 'Tamil',
        'tt' => 'Tatar',
        'te' => 'Telugu',
        'th' => 'Thai',
        'bo' => 'Tibetan',
        'ti' => 'Tigrinya',
        'to' => 'Tonga (Tonga Islands)',
        'ts' => 'Tsonga',
        'tn' => 'Tswana',
        'tr' => 'Turkish',
        'tk' => 'Turkmen',
        'tw' => 'Twi',
        'ug' => 'Uighur, Uyghur',
        'uk' => 'Ukrainian',
        'ur' => 'Urdu',
        'uz' => 'Uzbek',
        've' => 'Venda',
        'vi' => 'Vietnamese',
        'vo' => 'Volap_k',
        'wa' => 'Walloon',
        'cy' => 'Welsh',
        'fy' => 'Western Frisian',
        'wo' => 'Wolof',
        'xh' => 'Xhosa',
        'yi' => 'Yiddish',
        'yo' => 'Yoruba',
        'za' => 'Zhuang, Chuang',
        'zu' => 'Zulu'
    ],
    'us_states' => [
        'AL'=>'Alabama',
        'AK'=>'Alaska',
        'AZ'=>'Arizona',
        'AR'=>'Arkansas',
        'CA'=>'California',
        'CO'=>'Colorado',
        'CT'=>'Connecticut',
        'DE'=>'Delaware',
        'DC'=>'District of Columbia',
        'FL'=>'Florida',
        'GA'=>'Georgia',
        'HI'=>'Hawaii',
        'ID'=>'Idaho',
        'IL'=>'Illinois',
        'IN'=>'Indiana',
        'IA'=>'Iowa',
        'KS'=>'Kansas',
        'KY'=>'Kentucky',
        'LA'=>'Louisiana',
        'ME'=>'Maine',
        'MD'=>'Maryland',
        'MA'=>'Massachusetts',
        'MI'=>'Michigan',
        'MN'=>'Minnesota',
        'MS'=>'Mississippi',
        'MO'=>'Missouri',
        'MT'=>'Montana',
        'NE'=>'Nebraska',
        'NV'=>'Nevada',
        'NH'=>'New Hampshire',
        'NJ'=>'New Jersey',
        'NM'=>'New Mexico',
        'NY'=>'New York',
        'NC'=>'North Carolina',
        'ND'=>'North Dakota',
        'OH'=>'Ohio',
        'OK'=>'Oklahoma',
        'OR'=>'Oregon',
        'PA'=>'Pennsylvania',
        'RI'=>'Rhode Island',
        'SC'=>'South Carolina',
        'SD'=>'South Dakota',
        'TN'=>'Tennessee',
        'TX'=>'Texas',
        'UT'=>'Utah',
        'VT'=>'Vermont',
        'VA'=>'Virginia',
        'WA'=>'Washington',
        'WV'=>'West Virginia',
        'WI'=>'Wisconsin',
        'WY'=>'Wyoming',
    ],
    'language_levels' => [
        ['value' => '0', 'label' => 'Basic'],
        ['value' => '1', 'label' => 'Conversational'],
        ['value' => '2', 'label' => 'Fluent'],
    ],
    'babysitter_skills' => [
        ['value' => 'own_car', 'label' => 'Own car'],
        ['value' => 'holiday_nanny', 'label' => 'Holiday nanny'],
        ['value' => 'event_babysitter', 'label' => 'Event babysitter'],
        ['value' => 'language_or_special_tutoring', 'label' => 'Language or special tutoring'],
        ['value' => 'weekend_babysitter', 'label' => 'Weekend babysitter'],
        ['value' => 'flexible_hours', 'label' => 'Flexible hours'],
        ['value' => 'flight_travel_babysitting', 'label' => 'Flight travel babysitting'],
    ],
    'babysitter_day_night_cutoff' => 17,  // availability divider between day and night blocks
    'babysitter_book_duration' => [
        '2' => '2 hrs',
        '2.5' => '2.5 hrs',
        '3' => '3 hrs',
        '3.5' => '3.5 hrs',
        '4' => '4 hrs',
        '4.5' => '4.5 hrs',
        '5' => '5 hrs',
        '6' => '6 hrs',
        '7' => '7 hrs',
        '8' => '8 hrs',
        '9' => '9 hrs',
        '10' => '10 hrs',
        '12' => '12 hrs',
        '24' => 'all day',
        '48' => '2 days',
    ],
    'babysitter_backgrounds' => [
        ['value' => '1.jpg', 'label' => '1'],
        ['value' => '2.jpg', 'label' => '2'],
        ['value' => '3.jpg', 'label' => '3'],
        ['value' => '4.jpg', 'label' => '4'],
        ['value' => '5.jpg', 'label' => '5'],
        ['value' => '6.jpg', 'label' => '6'],
        ['value' => '7.jpg', 'label' => '7'],
        ['value' => '8.jpg', 'label' => '8'],
        ['value' => '9.jpg', 'label' => '9'],
        ['value' => '10.jpg', 'label' => '10'],
    ],

    'interview_hours' => [
        ['value' => '07:00', 'label' => '7:00'],
        ['value' => '07:30', 'label' => '7:30'],
        ['value' => '08:00', 'label' => '8:00'],
        ['value' => '08:30', 'label' => '8:30'],
        ['value' => '09:00', 'label' => '9:00'],
        ['value' => '09:30', 'label' => '9:30'],
        ['value' => '10:00', 'label' => '10:00'],
        ['value' => '10:30', 'label' => '10:30'],
        ['value' => '11:00', 'label' => '11:00'],
        ['value' => '11:30', 'label' => '11:30'],
        ['value' => '12:00', 'label' => '12:00'],
        ['value' => '12:30', 'label' => '12:30'],
        ['value' => '13:00', 'label' => '13:00'],
        ['value' => '13:30', 'label' => '13:30'],
        ['value' => '14:00', 'label' => '14:00'],
        ['value' => '14:30', 'label' => '14:30'],
        ['value' => '15:00', 'label' => '15:00'],
        ['value' => '15:30', 'label' => '15:30'],
        ['value' => '16:00', 'label' => '16:00'],
        ['value' => '16:30', 'label' => '16:30'],
        ['value' => '17:00', 'label' => '17:00'],
        ['value' => '17:30', 'label' => '17:30'],
        ['value' => '18:00', 'label' => '18:00'],
        ['value' => '18:30', 'label' => '18:30'],
        ['value' => '19:00', 'label' => '19:00'],
        ['value' => '19:30', 'label' => '19:30'],
        ['value' => '20:00', 'label' => '20:00'],
    ]
];
